=== ckxng/pr_home_bundle/Resources/private/fixture/directory.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:od="urn:schemas-microsoft-com:officedata">
<xsd:element name="dataroot">
<xsd:complexType>
<xsd:sequence>
<xsd:element ref="directory" minOccurs="0" maxOccurs="unbounded"/>
</xsd:sequence>
<xsd:attribute name="generated" type="xsd:dateTime"/>
</xsd:complexType>
</xsd:element>
<xsd:element name="directory">
<xsd:annotation>
<xsd:appinfo/>
</xsd:annotation>
<xsd:complexType>
<xsd:sequence>
<xsd:element name="people_ID" minOccurs="1" od:jetType="autonumber" od:sqlSType="int" od:autoUnique="yes" od:nonNullable="yes" type="xsd:int"/>
<xsd:element name="families_ID" minOccurs="1" od:jetType="autonumber" od:sqlSType="int" od:autoUnique="yes" od:nonNullable="yes" type="xsd:int"/>
<xsd:element name="last_name" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="first_name" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="person_type_name" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="relationship_type_name" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="address_1" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="address_2" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="city" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="state" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="zipcode" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="country" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="families_email" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="families_phone" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="people_phone" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="people_email" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="birthday" minOccurs="0" od:jetType="datetime" od:sqlSType="datetime" type="xsd:dateTime"/>
<xsd:element name="anniversary" minOccurs="0" od:jetType="datetime" od:sqlSType="datetime" type="xsd:dateTime"/>
</xsd:sequence>
</xsd:complexType>
</xsd:element>
</xsd:schema>

=== ckxng/pr_home_bundle/Resources/private/directory.xml
<?xml version="1.0" encoding="UTF-8"?>
<dataroot xmlns:od="urn:schemas-microsoft-com:officedata" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xsi:noNamespaceSchemaLocation="directory.xsd" generated="2013-04-04T21:54:21">
<directory>
<people_ID>1</people_ID>
<families_ID>2</families_ID>
<family_name>King</family_name>
<last_name>King</last_name>
<first_name>Cameron</first_name>
<person_type_name>Member</person_type_name>
<relationship_type_name>Head</relationship_type_name>
<sort>100</sort>
<address_1>1300 Raines St</address_1>
<city>Arlington</city>
<state>TX</state>
<zipcode>76010</zipcode>
<country>USA</country>
<people_phone>(682) 999-0991</people_phone>
<people_email>cking@ckxng.com</people_email>
<birthday>1986-07-14T00:00:00</birthday>
<anniversary>2005-12-31T00:00:00</anniversary>
</directory>
<directory>
<people_ID>2</people_ID>
<families_ID>2</families_ID>
<family_name>King</family_name>
<last_name>King</last_name>
<first_name>Megan</first_name>
<person_type_name>Member</person_type_name>
<relationship_type_name>Spouse</relationship_type_name>
<sort>200</sort>
<address_1>1300 Raines St</address_1>
<city>Arlington</city>
<state>TX</state>
<zipcode>76010</zipcode>
<country>USA</country>
<people_phone>(682) 999-0981</people_phone>
<people_email>megan@uniquekings.com</people_email>
<birthday>1981-09-02T00:00:00</birthday>
<anniversary>2005-12-31T00:00:00</anniversary>
</directory>
<directory>
<people_ID>4</people_ID>
<families_ID>2</families_ID>
<family_name>King</family_name>
<last_name>King</last_name>
<first_name>Mason</first_name>
<person_type_name>Child</person_type_name>
<relationship_type_name>Child</relationship_type_name>
<sort>700</sort>
<address_1>1300 Raines St</address_1>
<city>Arlington</city>
<state>TX</state>
<zipcode>76010</zipcode>
<country>USA</country>
<birthday>2012-04-20T00:00:00</birthday>
</directory>
<directory>
<people_ID>3</people_ID>
<families_ID>2</families_ID>
<family_name>King</family_name>
<last_name>King</last_name>
<first_name>Brooklyn</first_name>
<person_type_name>Child</person_type_name>
<relationship_type_name>Child</relationship_type_name>
<sort>700</sort>
<address_1>1300 Raines St</address_1>
<city>Arlington</city>
<state>TX</state>
<zipcode>76010</zipcode>
<country>USA</country>
<birthday>2009-07-10T00:00:00</birthday>
</directory>
</dataroot>
